// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN5G1UPy-7BR9JIQxjEYLEmLjftCYeIQQ',
    appId: '1:1095319370974:web:8b7e109dd898b9b86b964f',
    messagingSenderId: '1095319370974',
    projectId: 'jawara-apps-16fcc',
    authDomain: 'jawara-apps-16fcc.firebaseapp.com',
    storageBucket: 'jawara-apps-16fcc.firebasestorage.app',
    measurementId: 'G-RCTXFKTVG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PjVNCJFvsy-NAiiPKh5JaF3jMQziDjQ',
    appId: '1:1095319370974:android:ed87eca9321493356b964f',
    messagingSenderId: '1095319370974',
    projectId: 'jawara-apps-16fcc',
    storageBucket: 'jawara-apps-16fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuVVlcGkBe7Uz3IFFQ0sdzUgtlNspuhy4',
    appId: '1:1095319370974:ios:7fa86542a2abe51f6b964f',
    messagingSenderId: '1095319370974',
    projectId: 'jawara-apps-16fcc',
    storageBucket: 'jawara-apps-16fcc.firebasestorage.app',
    iosBundleId: 'com.example.jawaramobile1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuVVlcGkBe7Uz3IFFQ0sdzUgtlNspuhy4',
    appId: '1:1095319370974:ios:7fa86542a2abe51f6b964f',
    messagingSenderId: '1095319370974',
    projectId: 'jawara-apps-16fcc',
    storageBucket: 'jawara-apps-16fcc.firebasestorage.app',
    iosBundleId: 'com.example.jawaramobile1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN5G1UPy-7BR9JIQxjEYLEmLjftCYeIQQ',
    appId: '1:1095319370974:web:e17939817739d2546b964f',
    messagingSenderId: '1095319370974',
    projectId: 'jawara-apps-16fcc',
    authDomain: 'jawara-apps-16fcc.firebaseapp.com',
    storageBucket: 'jawara-apps-16fcc.firebasestorage.app',
    measurementId: 'G-2HBXCTCRT6',
  );
}
